/**
 * @2017-1-18 15:28:25
 * grid 的 types
 */
export const GETTER_LOADING = 'GETTER_LOADING'
export const CHANGE_LOADING = 'CHANGE_LOADING'

export const GETTER_SORT = 'GETTER_SORT'
export const CHANGE_SORT = 'CHANGE_SORT'

export const GETTER_CURRENT_SORT_FIELD = 'GETTER_CURRENT_SORT_FIELD'
export const CHANGE_CURRENT_SORT_FIELD = 'CHANGE_CURRENT_SORT_FIELD'

export const CHANGE_CURRENT_SORT_TYPE = 'CHANGE_CURRENT_SORT_TYPE'

export const GETTER_GRID_DATA = 'GETTER_GRID_DATA'

export const GETTER_GRID_COLUMN = 'GETTER_GRID_COLUMN'
export const CHANGE_GRID_COLUMN = 'CHANGE_GRID_COLUMN'

export const GETTER_GRID_REQUEST_URL = 'GETTER_GRID_URL'

export const GETTER_GRID_REQUEST_PARAM = 'GETTER_GRID_REQUEST_PARAM'

export const CHANGE_GRID_REQUEST_PARAM = 'CHANGE_GRID_REQUEST_PARAM'

export const GETTER_GRID_HEADER_CLASS = 'GETTER_GRID_HEADER_CLASS'

export const ACTION_SORT_BY_FIELD = 'ACTION_SORT_BY_FIELD'
